[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyseis"
version = "0.1.0"
description = "I/O components for PySeis"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: AGPL v3.0",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "dask",
    "pyarrow",
    "pyyaml",
    "zarr",
    "matplotlib",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[project.scripts]
pyseis-view = "pyseis.visualization.viewer:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pyseis = ["templates/schemas/*.yaml", "segd/*.yaml", "segd/*/*.yaml", "segy/*.yaml", "segy/*/*.yaml"]

