import numpy as np

su_header_dtype = np.dtype([
('tracl', np.int32),
('tracr', np.int32),
('fldr', np.int32),
('tracf', np.int32),
('ep', np.int32),
('cdp', np.int32),
('cdpt', np.int32),
('trid', np.int16),
('nvs', np.int16),
('nhs', np.int16),
('duse', np.int16),
('offset', np.int32),
('gelev', np.int32),
('selev', np.int32),
('sdepth', np.int32),
('gdel', np.int32),
('sdel', np.int32),
('swdep', np.int32),
('gwdep', np.int32),
('scalel', np.int16),
('scalco', np.int16),
('sx', np.int32),
('sy', np.int32),
('gx', np.int32),
('gy', np.int32),
('counit', np.int16),
('wevel', np.int16),
('swevel', np.int16),
('sut', np.int16),
('gut', np.int16),
('sstat', np.int16),
('gstat', np.int16),
('tstat', np.int16),
('laga', np.int16),
('lagb', np.int16),
('delrt', np.int16),
('muts', np.int16),
('mute', np.int16),
('ns', np.uint16),
('dt', np.uint16),
('gain', np.int16),
('igc', np.int16),
('igi', np.int16),
('corr', np.int16),
('sfs', np.int16),
('sfe', np.int16),
('slen', np.int16),
('styp', np.int16),
('stas', np.int16),
('stae', np.int16),
('tatyp', np.int16),
('afilf', np.int16),
('afils', np.int16),
('nofilf', np.int16),
('nofils', np.int16),
('lcf', np.int16),
('hcf', np.int16),
('lcs', np.int16),
('hcs', np.int16),
('year', np.int16),
('day', np.int16),
('hour', np.int16),
('minute', np.int16),
('sec', np.int16),
('timebas', np.int16),
('trwf', np.int16),
('grnors', np.int16),
('grnofr', np.int16),
('grnlof', np.int16),
('gaps', np.int16),
('otrav', np.int16), #179,180
('d1', np.float32), #181,184
('f1', np.float32), #185,188
('d2', np.float32), #189,192
('f2', np.float32), #193, 196
('ShotPoint', np.int32), #197,200
('unscale', np.int16), #201, 204
('TraceValueMeasurementUnit', np.int16),
('TransductionConstantMantissa', np.int32),
('TransductionConstantPower', np.int16),
('TransductionUnit', np.int16),
('TraceIdentifier', np.int16),
('ScalarTraceHeader', np.int16),
('SourceType', np.int16),
('SourceEnergyDirectionMantissa', np.int32),
('SourceEnergyDirectionExponent', np.int16),
('SourceMeasurementMantissa', np.int32),
('SourceMeasurementExponent', np.int16),
('SourceMeasurementUnit', np.int16),
('UnassignedInt1', np.int32),
('ns1', np.int32),
])

segy_textual_header_dtype = np.dtype([('TFH', (np.str,   80))])

segy_binary_header_dtype = np.dtype([
	('jobid', 'i4'),
	('lino', 'i4'),
	('reno', 'i4'),
	('ntrpr', 'i2'), # mandatory (prestack)
	('nart', 'i2'), # mandatory (prestack)
	('hdt', 'u2'), # mandatory (all)
	('dto', 'u2'),
	('hns', 'u2'), # mandatory (all)
	('nso', 'u2'),
	('format', 'i2'), # mandatory (all)
	('fold', 'i2'), # strongly recommended
	('tsort', 'i2'), # strongly recommended
	('vscode', 'i2'),
	('hsfs', 'i2'),
	('hsfe', 'i2'),
	('hslen', 'i2'),
	('hstyp', 'i2'),
	('schn', 'i2'),
	('hstas', 'i2'),
	('hstae', 'i2'),
	('htatyp', 'i2'),
	('hcorr', 'i2'),
	('bgrcv', 'i2'),
	('rcvm', 'i2'),
	('mfeet', 'i2'), # strongly recommended
	('polyv', 'i2'),
	('vpol', 'i2'),
	('unassigned_1', (np.str,   240)),
	('segyrev', 'i2'), # mandatory (all)
	('fixedlen', 'i2'), # mandatory (all)
	('numhdr', 'i2'), # mandatory (all)
	('unassigned_2', (np.str,   94)),
])

segy_trace_header_dtype = np.dtype([
	('tracl',  'i4'), # strongly recommended
	('tracr',  'i4'),
	('fldr',   'i4'), # strongly recommended
	('tracf',  'i4'), # strongly recommended
	('ep',     'i4'),
	('cdp',    'i4'),
	('cdpt',   'i4'),
	('trid',   'i2'), # strongly recommended
	('nvs',    'i2'),
	('nhs',    'i2'),
	('duse',   'i2'),
	('offset', 'i4'),
	('gelev',  'i4'),
	('selev',  'i4'),
	('sdepth', 'i4'),
	('gdel',   'i4'),
	('sdel',   'i4'),
	('swdep',  'i4'),
	('gwdep',  'i4'),
	('scalel', 'i2'),
	('scalco', 'i2'),
	('sx',     'i4'),
	('sy',     'i4'),
	('gx',     'i4'),
	('gy',     'i4'),
	('counit', 'i2'),
	('wevel',   'i2'),
	('swevel',  'i2'),
	('sut',     'i2'),
	('gut',     'i2'),
	('sstat',   'i2'),
	('gstat',   'i2'),
	('tstat',   'i2'),
	('laga',    'i2'),
	('lagb',    'i2'),
	('delrt',   'i2'),
	('muts',    'i2'),
	('mute',    'i2'),
	('ns',      'i2'), # strongly recommended
	('dt',      'i2'), # strongly recommended
	('gain',    'i2'),
	('igc',    'i2'),
	('igi',    'i2'),
	('corr',   'i2'),
	('sfs',    'i2'),
	('sfe',    'i2'),
	('slen',   'i2'),
	('styp',   'i2'),
	('stas',   'i2'),
	('stae',   'i2'),
	('tatyp',  'i2'),
	('afilf',  'i2'),
	('afils',  'i2'),
	('nofilf', 'i2'),
	('nofils', 'i2'),
	('lcf',    'i2'),
	('hcf',    'i2'),
	('lcs',    'i2'),
	('hcs',    'i2'),
	('year',   'i2'),
	('day',    'i2'),
	('hour',   'i2'),
	('minute', 'i2'),
	('sec',    'i2'),
	('timbas', 'i2'),
	('trwf',   'i2'),
	('grnors', 'i2'),
	('grnofr', 'i2'),
	('grnlof', 'i2'),
	('gaps',   'i2'),
	('otrav',  'i2'),
	('cdpx',   'i4'),
	('cdpy',   'i4'),
	('iline',  'i4'),
	('xline',  'i4'),
	('shnum',  'i4'),
	('shsca',  'i2'),
	('tval',   'i2'),
	('tconst4', 'i4'),
	('tconst2', 'i2'),
	('tunits', 'i2'),
	('device', 'i2'),
	('tscalar', 'i2'),
	('stype',  'i2'),
	('sendir', 'i4'),
	('unknown', 'i2'),
	('smeas4', 'i4'),
	('smeas2', 'i2'),
	('smeasu', 'i2'),
	('unass1', 'i4'),
	('unass2', 'i4'),
	])

